elCicdDefaults:
  objName: stationdemo

elCicdDefs:
  OBJ_NAME: stationdemo
  READINESS_PROBE:
    httpGet:
      path: /${OBJ_NAME}-${SDLC_ENV}/actuator/health/StationHealthCheck
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 50
    periodSeconds: 5

elCicdDefs-prod:
  READINESS_PROBE:
    httpGet:
      path: /${OBJ_NAME}/actuator/health/StationHealthCheck
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 50
    periodSeconds: 5

elCicdTemplates:
- templateName: deploymentService
  env:
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /${OBJ_NAME}-${SDLC_ENV}
  readinessProbe:
    ${READINESS_PROBE}
  limitsMemory: 2000Mi
  prometheus:
    port: 15345

- templateName: ingress
