elCicdDefaults:
  objName: stationdemo

elCicdDefs:
  ROOT_PATH: $<OBJ_NAME>-$<SDLC_ENV>
  OBJ_NAME: $<OBJ_NAME>
  PORT: 8080
  READINESS_PROBE:
    httpGet:
      path: /$<ROOT_PATH>/actuator/health/StationHealthCheck
      port: $<PORT>
    initialDelaySeconds: 10
    failureThreshold: 50
    periodSeconds: 5

elCicdDefs-prod:
  ROOT_PATH: $<OBJ_NAME>

elCicdTemplates:
- templateName: deploymentServiceIngress
  env:
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /$<ROOT_PATH>
  readinessProbe:
    $<READINESS_PROBE>
  limitsMemory: 2000Mi
  prometheus:
    port: 15345
  rules:
  - host: $<ROOT_PATH>.apps-crc.testing
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: $<OBJ_NAME>
            port:
              number: $<PORT>
  
