elCicdDefaults:
  objName: stationdemo

elCicdDefs:
  ROOT_PATH: $<OBJ_NAME>-$<SDLC_ENV>
  OBJ_NAME: stationdemo
  READINESS_PROBE:
    httpGet:
      path: /$<ROOT_PATH>/actuator/health/StationHealthCheck
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 50
    periodSeconds: 5

elCicdDefs-prod:
  ROOT_PATH: $<OBJ_NAME>

elCicdTemplates:
- templateName: deploymentServiceIngress
  env:
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /$<ROOT_PATH>
  readinessProbe:
    $<READINESS_PROBE>
  limitsMemory: 2000Mi
  prometheus:
    port: 15345
