templateVars:
  APP_NAME: stationdemo

templates:
- templateName: deploymentService
  appName: ${APP_NAME}
  env:
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /${APP_NAME}-${SDLC_ENV}
  readinessProbe:
    httpGet:
      path: /${APP_NAME}-${SDLC_ENV}/actuator/health/StationHealthCheck
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 50
    periodSeconds: 5
  limitsCpu: 500m
  limitsMemory: 1000Mi
  prometheus:
    port: 15345
- templateName: ingress
  appName: ${APP_NAME}
